qemu-system-x86_64 \
    -machine q35,vmport=off \
    -enable-kvm \
    -cpu host \
    -smp 4 \
    -m 8192 \
    -netdev user,id=net0 \
    -device virtio-net-pci,netdev=net0 \
    -device virtio-vga-gl \
    -display sdl,gl=on \
    -snapshot \
    -drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2-ovmf/x64/OVMF_CODE.4m.fd \
    -drive if=pflash,format=raw,file=/usr/share/edk2-ovmf/x64/OVMF_VARS.4m.fd \
    -drive file=image.raw,format=raw,if=virtio
